### PR TITLE
Update your fork

### PR DESCRIPTION
**Pull request by Bluscream**
Use this: https://github.com/nothub/meteor-client/compare/nothub:master...MeteorDevelopment:master?expand=1

### CODE REVIEW

**Comment by nothub** [comment]
Hey, i am not sure what you want me to do.
There should be no need to update my fork, there are no conflicts with the base branch.

**Comment by Bluscream** [comment]
i want to use a jar with your changes, but if i do that i will miss out on everything that the source branch has changed/fixed

**Comment by Bluscream** [comment]
someone got a problem compiling your PR
```
Big Iron — Today at 10:08 PM
getting a build fail with this killaura pr
meteor-client-master\src\main\java\meteordevelopment\meteorclient\systems\modules\combat\KillAura.java:243: error: cannot find symbol
            InvUtils.swap(weaponResult.getSlot(), false);
                                      ^
  symbol:   method getSlot()
  location: variable weaponResult of type FindItemResult
the guy definitely has to fix something
his PR is from October, lots of stuff changed
```

**Comment by nothub** [comment]
I am not sure what your friend is trying to build. I merged the upstream on [this](https://github.com/nothub/meteor-client/tree/merged-upstream) branch for you but i do not really plan to provide much support for it. This branch _master_ and the other branch _merged-upstream_ both build fine for me.

**Pull request closed without merging**
